### PR TITLE
symbiflow: add nextpnr sub tool

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

This PR adds nextpnr as a subtool to have support it in fpga-tool-perf

### CODE REVIEW

**Comment by mithro** [comment]
@acomodi Should this be against the upstream @olofk repo?

**Comment by acomodi** [comment]
@mithro Sure, first I would like to test it in the SymbiFlow fork. Once it works fine I think we can open a PR to integrate the `symbiflow` branch upstream.

**Comment by mithro** [comment]
Make sure you open an issue then to send it upstream.

**Comment by olofk** [comment]
Happy to take a look at a PR against upstream edalize when you're ready

**Comment by acomodi** [comment]
@olofk Ok, I am preparing the PR, I'll open it by tomorrow.

One question, do you prefer to have a single PR ore multiple PRs that enable symbiflow, nextpnr and apply some other patches?

**Pull request merged**
